### ISSUE TITLE
Error installing plugins

### ISSUE THREAD

**Issue by djjuhasz** [BmanDesignsCanada/LiSpeak#78]
<pre>
./lispeak -p GeditControl
Recieved: /tmp/LiSpeak_FILES/tmp.tar.gz
Gathering
Traceback (most recent call last):
  File "./lispeak", line 1262, in <module>
    downloadPackage(args.p)
  File "./lispeak", line 469, in downloadPackage
    installPlugin('/tmp/LiSpeak_FILES/tmp.tar.gz')
  File "./lispeak", line 850, in installPlugin
    data = getPluginData(path)
  File "./lispeak", line 838, in getPluginData
    tar = tarfile.open(mode='r:gz',fileobj=file(path))
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1727, in gzopen
    **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1705, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1574, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2338, in next
    raise ReadError("empty file")
tarfile.ReadError: empty file
</pre>

I got the same error from the ./lispeak --setup on the Plugin install step.

**Comment by BmanDesignsCanada** [comment]
I have re-uploaded all the plugins and LiSpeak now install properly.
