### ISSUE TITLE
Error, Please help...

### ISSUE THREAD

**Issue by jamieduk** [BmanDesignsCanada/LiSpeak#86]
Traceback (most recent call last):
  File "./lispeak", line 1246, in <module>
    setup()
  File "./lispeak", line 425, in setup
    call("make")
  File "./lispeak", line 593, in call
    subprocess.check_call(cmd, stdout=devnull, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2

**Comment by BmanDesignsCanada** [comment]
This project is dead.
